from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field, field_validator


class ChatQuery(BaseModel):
    message: str = Field(..., description="The user query input to route to support agents.")
    session_id: Optional[str] = Field(None, description="The unique session identifier for conversation state mapping.")
    conversation_id: Optional[str] = Field(None, description="The unique conversation thread ID.")

    @field_validator("message")
    @classmethod
    def validate_message(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Message cannot be empty or consist only of whitespace.")
        if len(v) > 1000:
            raise ValueError("Message cannot exceed 1000 characters.")
        return v


class ChatResponse(BaseModel):
    intent: str = Field(..., description="The detected customer intent.")
    agent: Optional[str] = Field(None, description="The agent selected to handle the query.")
    response: Optional[str] = Field(None, description="The response generated by the selected agent.")
    message: Optional[str] = Field(None, description="The clarification message if the intent is unknown.")
    sources: Optional[List[dict]] = Field(None, description="The list of unique RAG source documents used for grounding.")
    conversation_id: Optional[str] = Field(None, description="The unique conversation thread ID.")


class ConversationCreate(BaseModel):
    session_id: Optional[str] = None
    user_id: Optional[str] = None
    title: Optional[str] = None


class ConversationResponse(BaseModel):
    conversation_id: str
    session_id: Optional[str] = None
    user_id: Optional[str] = None
    title: Optional[str] = None
    created_at: datetime
    updated_at: datetime


class MessageResponse(BaseModel):
    message_id: str
    conversation_id: str
    role: str
    content: str
    intent: Optional[str] = None
    agent: Optional[str] = None
    sources: Optional[List[dict]] = None
    created_at: datetime
