from typing import Optional, List
from pydantic import BaseModel, Field, field_validator


class ChatQuery(BaseModel):
    message: str = Field(..., description="The user query input to route to support agents.")

    @field_validator("message")
    @classmethod
    def validate_message(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Message cannot be empty or consist only of whitespace.")
        if len(v) > 1000:
            raise ValueError("Message cannot exceed 1000 characters.")
        return v


class ChatResponse(BaseModel):
    intent: str = Field(..., description="The detected customer intent.")
    agent: Optional[str] = Field(None, description="The agent selected to handle the query.")
    response: Optional[str] = Field(None, description="The response generated by the selected agent.")
    message: Optional[str] = Field(None, description="The clarification message if the intent is unknown.")
    sources: Optional[List[dict]] = Field(None, description="The list of unique RAG source documents used for grounding.")
